version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    container_name: dockge
    ports:
      - 9001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /apps/docker/dockge/data:/app/data
      - /apps/docker:/apps/docker
    environment:
      - DOCKGE_STACKS_DIR=/apps/docker
